import productImageDrinkHL from './assets/product/Highlands-coffee.jpg';
import productImageTech from './assets/product/galaxys23.jpg';
import productImageFood from './assets/product/am-thuc-phap-5_1642581433.jpg';
import productImageDrinkPL from './assets/product/PhucLong.png';
import productImageFashionNike from './assets/product/ma-giam-gia-nike.jpg';
import productImageFashionCoolmate from './assets/product/coolmate-shark-tank-9.jpg';

export const Details = [
    {
        id: 1,
        title: "Voucher giảm 25k Highlands",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "20",
        productImage: productImageDrinkHL,
    },

    {
        id: 2,
        title: "Voucher giảm 2 triệu Samsung Galaxy S23",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        productImage: productImageTech,
    },

    {
        id: 3,
        title: "Voucher giảm 20% set Valentine's special menu",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        productImage: productImageFood,
    },

    {
        id: 4,
        title: "Voucher giảm thêm 110k trên giá đã giảm",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        productImage: productImageFashionNike,
    },

    {
        id: 5,
        title: "Voucher giảm 110k cho đơn hàng từ 550k",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        productImage: productImageFashionCoolmate,
    },

    {
        id: 6,
        title: "Voucher giảm 20k đồ uống Phúc Long siêu chất",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        productImage: productImageDrinkPL,
    },

    {
        id: 7,
        title: "Voucher giảm 2 triệu Samsung Galaxy S23 Series",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.", time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        productImage: productImageTech,
    },

    {
        id: 8,
        title: "Voucher giảm 20% set Valentine's special menu",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        productImage: productImageFood,
    },
]