import productImageDrinkHL from './assets/product/Highlands-coffee.jpg';
import productImageTech from './assets/product/galaxys23.jpg';
import productImageFood from './assets/product/am-thuc-phap-5_1642581433.jpg';
import productImageDrinkPL from './assets/product/PhucLong.png';
import productImageFashionNike from './assets/product/ma-giam-gia-nike.jpg';
import productImageFashionCoolmate from './assets/product/coolmate-shark-tank-9.jpg';



export const PRODUCTS = [

    {
        id: 1,
        type: "Thức uống",
        duration: {
            startDate: new Date(2023, 2 - 1, 1),
            endDate: new Date(2023, 6 - 1, 30),
        },
        title: "Voucher giảm 25k Highlands",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland trực tiếp tại cửa hàng sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng khi mua trực tiếp ở các chi nhánh khu vực Hồ Chí Minh, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong và sân bay Tân Sơn Nhất",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "20",
        image: productImageDrinkHL,
    },
    {
        id: 2,
        type: "Công nghệ",
        duration: "01/07/2023 - 15/07/2023",
        title: "Nhận Voucher 2 triệu mua Samsung Galaxy S23",
        description1: "Voucher được áp dụng khi mua các sản phẩm Samsung Galaxy S23 Series tại Hệ thống CellphoneS ở TP.Hồ Chí Minh.",
        description2: "Do giới hạn số lượng voucher, chương trình có thể kết thúc trước thời gian dự kiến.",
        description3: "Voucher không có giá trị quy đổi thành tiền mặt hoặc hoàn trả tiền thừa (nếu có)",
        condition1: " Mỗi khách hàng được nhận tối đa 01 voucher.",
        condition2: "Áp dụng khi mua sản phẩm Samsung Galaxy S23 Series tại Hệ thống cửa hàng CellphoneS ở TP.Hồ Chí Minh.",
        condition3: "Một voucher chỉ được áp dụng được 01 (một) lần duy nhất, không được cấp lại/đổi trả cho dù có bất kỳ lý do phát sinh liên quan trên đơn hàng.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageTech,
    },
    {
        id: 3,
        type: "Nhà hàng",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm 20% set Valentine's special menu",
        description1: "Giảm 20% Set Valentine’s Special Menu tại Nhà hàng Ruby (Giá gốc: 2,500,000đ/set/02 người chỉ còn 2,000,000đ/set/02 người).",
        description2: "Do giới hạn số lượng voucher, chương trình có thể kết thúc trước thời gian dự kiến.",
        description3: "Voucher không có giá trị quy đổi thành tiền mặt hoặc hoàn trả tiền thừa (nếu có)",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác.",
        condition3: "Chỉ áp dụng khi trực tiếp đến nhà hàng Ruby ở các chi nhánh tại TP.Hồ Chí Minh.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageFood,
    },
    {
        id: 4,
        type: "Thời trang",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm thêm 110k trên giá đã giảm",
        description1: "Voucher giảm 110,000đ áp dụng khi trực tiếp mua sản phẩm của thương hiệu Nike ở các chi nhánh tại TP.Hồ Chí Minh.",
        description2: "Do giới hạn số lượng voucher, chương trình có thể kết thúc trước thời gian dự kiến.",
        description3: "Voucher không có giá trị quy đổi thành tiền mặt hoặc hoàn trả tiền thừa (nếu có)",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác.",
        condition3: "Chỉ áp dụng khi mua sản phẩm trực tiếp ở các chi nhánh Nike tại TP.Hồ Chí Minh.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageFashionNike,
    },
    {
        id: 5,
        type: "Thời trang",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm 110k cho đơn hàng từ 550k",
        description1: "Voucher giảm 100,000đ áp dụng cho đơn hàng từ 550,000đ khi mua sắm trực tiếp ở các chi nhánh Coolmate tại TP.Hồ Chí Minh.",
        description2: "Do giới hạn số lượng voucher, chương trình có thể kết thúc trước thời gian dự kiến.",
        description3: "Voucher không có giá trị quy đổi thành tiền mặt hoặc hoàn trả tiền thừa (nếu có)",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác.",
        condition3: "Chỉ áp dụng khi mua sản phẩm trực tiếp ở các chi nhánh Nike tại TP.Hồ Chí Minh.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageFashionCoolmate,
    },
    {
        id: 6,
        type: "Thức uống",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm 20k đồ uống Phúc Long siêu chất",
        description1: "Voucher giảm 20,000đ cho hóa đơn từ 55,000đ trở lên áp dụng khi mua sản phẩm trực tiếp tại các chi nhánh Phúc Long ở TP.Hồ Chí Minh.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Voucher không có giá trị quy đổi thành tiền mặt hoặc hoàn trả tiền thừa (nếu có)",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác",
        condition3: "Voucher chỉ áp dụng toàn quốc khi mua sản phẩm trực tiếp tại các chi nhánh Phúc Long ở TP.Hồ Chí Minh. Ngoại trừ sân bay Tân Sơn Nhất.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageDrinkPL,
    },
    {
        id: 7,
        type: "Công nghệ",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Nhận Voucher 2 triệu mua Samsung Galaxy S23",
        description1: "Voucher được áp dụng khi mua các sản phẩm Samsung Galaxy S23 Series tại Hệ thống CellphoneS ở TP.Hồ Chí Minh.",
        description2: "Do giới hạn số lượng voucher, chương trình có thể kết thúc trước thời gian dự kiến.",
        description3: "Voucher không có giá trị quy đổi thành tiền mặt hoặc hoàn trả tiền thừa (nếu có)",
        condition1: " Mỗi khách hàng được nhận tối đa 01 voucher.",
        condition2: "Áp dụng khi mua sản phẩm Samsung Galaxy S23 Series tại Hệ thống cửa hàng CellphoneS ở TP.Hồ Chí Minh.",
        condition3: "Một voucher chỉ được áp dụng được 01 (một) lần duy nhất, không được cấp lại/đổi trả cho dù có bất kỳ lý do phát sinh liên quan trên đơn hàng.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageTech,
    },
    {
        id: 8,
        type: "Nhà hàng",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm 20% set Valentine's special menu",
        description1: "Giảm 20% Set Valentine’s Special Menu tại Nhà hàng Ruby (Giá gốc: 2,500,000đ/set/02 người chỉ còn 2,000,000đ/set/02 người).",
        description2: "Do giới hạn số lượng voucher, chương trình có thể kết thúc trước thời gian dự kiến.",
        description3: "Voucher không có giá trị quy đổi thành tiền mặt hoặc hoàn trả tiền thừa (nếu có)",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác.",
        condition3: "Chỉ áp dụng khi trực tiếp đến nhà hàng Ruby ở các chi nhánh tại TP.Hồ Chí Minh.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageFood,
    },
    {
        id: 9,
        type: "Thức uống",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm 25k Highlands",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "20",
        image: productImageDrinkHL,
    },
    {
        id: 10,
        type: "Công nghệ",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm 2 triệu Samsung Galaxy S23",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageTech,
    },
    {
        id: 11,
        type: "Nhà hàng",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm 20% set Valentine's special menu",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageFood,
    },
    {
        id: 12,
        type: "Thời trang",
        duration: {
            startDate: new Date(2023, 6, 1),
            endDate: new Date(2023, 6, 30),
        },
        title: "Voucher giảm thêm 110k trên giá đã giảm",
        description1: "Voucher áp dụng khi mua hóa đơn từ 120K đồ uống Highland sẽ được giảm 25K.",
        description2: "Khách hàng có thể trả thêm tiền để đổi ly cỡ nhỏ trong combo sang cỡ vừa hoặc lớn.",
        description3: "Không áp dụng cho sản phẩm Trà Nhiệt Đới / Trà Dưa Hấu Vải.",
        condition1: " Mỗi mã khuyến mãi chỉ được sử dụng 01 lần và chỉ áp dụng trên 01 hóa đơn.",
        condition2: "Không áp dụng cùng các chương trình khuyến mãi khác và các đối tác giao hàng.",
        condition3: "Voucher áp dụng toàn quốc, ngoại trừ các cơ sở: Highlands Coffee Dinh Độc Lập bên trong, Grand World Phú Quốc, VinWonders Phú Quốc và sân bay trên toàn quốc.",
        guide1: "Bước 1: Chọn voucher trên website Student Deal.",
        guide2: "Bước 2: Nhấn nút “Add Voucher” để nhận voucher.",
        guide3: "Bước 3: Vào My Vouchers và nhấn voucher đã nhận.",
        guide4: "Bước 4: Nó sẽ hiện ra mã Code.",
        guide5: "Bước 5: Xuất trình mã code của voucher tại cửa hàng được ủy quyền để sử dụng ưu đãi.",
        time: "Thời gian áp dụng: Từ 01/07/2023 đến hết 15/07/2023.",
        price: "50",
        image: productImageFashionNike,
    }

];



